### ISSUE TITLE
Problem with CPP

### ISSUE THREAD

**Issue by Giwrgosyea** [5g-empower/empower-lvnf-agent#1]
I have a soekris net5501 with Debian 7.11. I followed your installation guide for installing the lvnf-agent but after ./empower-lvnf-agent.py -c 192.168.100.158 -p 4422 -b br0 , 
I get : 
File "./empower-lvnf-agent.py", line 24, in <module>
    main()
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 507, in main
    args.listen)
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 139, in __init__
    self.bridge = bridge
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 220, in bridge
    self.addr = EtherAddress(get_hw_addr(bridge))
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/utils.py", line 46, in get_hw_addr
    struct.pack('256s', ifname[:15].encode('utf-8')))
IOError: [Errno 19] No such device

**Comment by rriggio** [comment]
it means that the br0 device does not exists. Did you follow the
instructions for configuring OVS? Do you see a br0 device?

R.

**Comment by Giwrgosyea** [comment]
Unfortunately no , i followed your instruction from your wiki step by step but , should i do anything else to configure br0 ? 
You dont provide any instructions to set the OVS in your wiki !

**Comment by rriggio** [comment]
did you follow this:

https://github.com/5g-empower/5g-empower.github.io/wiki/Setting-up-the-CPP

did you edit the interfaces files as described in the wiki? if so after you
reboot you should see a new interface names br0

R.

**Comment by Giwrgosyea** [comment]
I built OVS as a result I see br0 fixing my previous error, but now after ./empower-lvnf-agent.py -c 192.168.100.158 -p 4422 -b br0 
I get:
Traceback (most recent call last):
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/utils.py", line 64, in exec_cmd
    output, errs = proc.communicate(timeout=timeout)
TypeError: communicate() got an unexpected keyword argument 'timeout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./empower-lvnf-agent.py", line 24, in <module>
    main()
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 507, in main
    args.listen)
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 139, in __init__
    self.bridge = bridge
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 223, in bridge
    if not self.ports:
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/agent.py", line 182, in ports
    lines = exec_cmd(cmd).split('\n')
  File "/home/scan-cpp1/empower-lvnf-agent/empower/agent/utils.py", line 66, in exec_cmd
    except subprocess.TimeoutExpired:
AttributeError: 'module' object has no attribute 'TimeoutExpired'

**Comment by rriggio** [comment]
this is related to the python version. I think you are using a version
older than 3.3. I will add some instriuctions on the wiki to use
python 3.6 or newer.

R.

**Comment by Giwrgosyea** [comment]
This solved problem has been solved.
